### ISSUE TITLE
change AuthStatus

### ISSUE THREAD

**Issue by rdavis120** [numberjuani/ibkr-cp-api-client#12]
The message and server_info fields would not be present if the session is not authenticated and tickle is called.  I would propose making them serde default or Option<>.  

I also would propose using the same AuthStatus as the return type of ```pub async fn check_auth_status(&self)``` instead of ```Value```.

Please let me know if this would break your functionality.

```rust
pub struct AuthStatus {
    #[serde(rename = "MAC")]
    pub mac: String,
    pub authenticated: bool,
    pub competing: bool,
    pub connected: bool,
    #[serde(default)]
    pub message: String,
    #[serde(default)]
    pub server_info: ServerInfo,
}
```

**Comment by numberjuani** [comment]
Hi @rdavis120 both of those struct implement `Default` meaning if the keys are not in the json, they will deserialize to empty Strings. They will not make your application crash and you should still be able to catch that you're not authed

**Comment by rdavis120** [comment]
Ok. Are you ok with changing the return to AuthStatus?

**Comment by numberjuani** [comment]
Not sure I understand what you mean

**Comment by rdavis120** [comment]
Just to change:
```pub async fn check_auth_status(&self) -> Result<Value, reqwest::Error> {```

To:
```pub async fn check_auth_status(&self) -> Result<AuthStatus, reqwest::Error> {```

**Comment by numberjuani** [comment]
Sure, I must have forgotten
