### ISSUE TITLE
remove hyphens from crate name

### ISSUE THREAD

**Issue by rdavis120** [numberjuani/ibkr-cp-api-client#2]
Would you consider renaming the crate to not use the hyphen to simplify and avoid the issues with the "-" being changed to an underscore?  I used this to simplify the name:
ibkrcp = { git = "https://github.com/numberjuani/ibkr-cp-api-client.git", version = "0.1.0", package = "ibkr-cp-api-client" }

**Comment by numberjuani** [comment]
Hi @rdavis120 what is the issue with the underscore and dash? Nearly all crates in rust work that way. Also , you only have to type the crate name in cargo.toml, after that you can Alias it to be whatever you like when you import it

**Comment by rdavis120** [comment]
Sorry, there is no issue - I did the alias in the example.
