### ISSUE TITLE
get_security_definition_by_contract_id uses i32 instead of i64

### ISSUE THREAD

**Issue by rdavis120** [numberjuani/ibkr-cp-api-client#3]
I'm not sure if this was intentional in the design, but the FuturesContract and Contract models uses _i64_ for the conid field, whereas get_security_definition_by_contract_id accepts a vector of _i32_.  Therefore, if you do a search by futures by symbol search you receive i64, and then have to change it to i32 when looking up the security definition.

``` rust
pub async fn get_security_definition_by_contract_id(
        &self,
        contract_ids: Vec<i32>,
    )
    ...
```

``` rust
pub struct FuturesContract {
    pub conid: i64,
     ...
```

**Comment by numberjuani** [comment]
fixed
